name: pipeline-merge-workflow

# on:
#   pull_request:
#     branches:
#       - 'release*'
#     types: [closed]

on:
  push:

env:
  GITHUB_JSON:                  ${{ toJSON(github) }}
  SF_DEVHUB_CLIENTID:           ${{ secrets.SF_DEVHUB_CLIENTID }}
  SF_DEVHUB_KEY_BASE64:         ${{ secrets.SF_DEVHUB_KEY_BASE64 }}
  SF_DEVHUB_ORG_URL:            ${{ secrets.SF_DEVHUB_ORG_URL }}
  SF_INT_AUTH_URL:              ${{ secrets.SF_INT_AUTH_URL }}
  DEVHUB_ORG_USERNAME:          ${{ secrets.CICD_DEVHUB_USERNAME }}
  PACKAGE_NAME:                 ${{ secrets.PACKAGE_NAME }}
  DEVHUB_ALIAS:                 "devhub"
  INT_ALIAS:                    "int"
  SCRATCH_ORG_ALIAS:            "ci-scratch-org"

jobs:
  qa_deployment:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: test 1
        run: echo "qa env"

  uat_deployment:
    runs-on: ubuntu-latest
    environment: UAT
    needs: [qa_deployment]

    steps:
      - name : test 2
        run: echo "uat"

 